class QuranData {
  static const List<Map<String, dynamic>> surahs = [
    {'id': 1, 'name': 'Al-Fatihah', 'juz': 1},
    {'id': 2, 'name': 'Al-Baqarah', 'juz': 1},
    {'id': 3, 'name': 'Ali \'Imran', 'juz': 3},
    {'id': 4, 'name': 'An-Nisa\'', 'juz': 4},
    {'id': 5, 'name': 'Al-Ma\'idah', 'juz': 6},
    {'id': 6, 'name': 'Al-An\'am', 'juz': 7},
    {'id': 7, 'name': 'Al-A\'raf', 'juz': 8},
    {'id': 8, 'name': 'Al-Anfal', 'juz': 9},
    {'id': 9, 'name': 'At-Taubah', 'juz': 10},
    {'id': 10, 'name': 'Yunus', 'juz': 11},
    {'id': 11, 'name': 'Hud', 'juz': 11},
    {'id': 12, 'name': 'Yusuf', 'juz': 12},
    {'id': 13, 'name': 'Ar-Ra\'d', 'juz': 13},
    {'id': 14, 'name': 'Ibrahim', 'juz': 13},
    {'id': 15, 'name': 'Al-Hijr', 'juz': 14},
    {'id': 16, 'name': 'An-Nahl', 'juz': 14},
    {'id': 17, 'name': 'Al-Isra\'', 'juz': 15},
    {'id': 18, 'name': 'Al-Kahf', 'juz': 15},
    {'id': 19, 'name': 'Maryam', 'juz': 16},
    {'id': 20, 'name': 'Taha', 'juz': 16},
    {'id': 21, 'name': 'Al-Anbiya\'', 'juz': 17},
    {'id': 22, 'name': 'Al-Hajj', 'juz': 17},
    {'id': 23, 'name': 'Al-Mu\'minun', 'juz': 18},
    {'id': 24, 'name': 'An-Nur', 'juz': 18},
    {'id': 25, 'name': 'Al-Furqan', 'juz': 18},
    {'id': 26, 'name': 'Asy-Syu\'ara\'', 'juz': 19},
    {'id': 27, 'name': 'An-Naml', 'juz': 19},
    {'id': 28, 'name': 'Al-Qasas', 'juz': 20},
    {'id': 29, 'name': 'Al-\'Ankabut', 'juz': 20},
    {'id': 30, 'name': 'Ar-Rum', 'juz': 21},
    {'id': 31, 'name': 'Luqman', 'juz': 21},
    {'id': 32, 'name': 'As-Sajdah', 'juz': 21},
    {'id': 33, 'name': 'Al-Ahzab', 'juz': 21},
    {'id': 34, 'name': 'Saba\'', 'juz': 22},
    {'id': 35, 'name': 'Fatir', 'juz': 22},
    {'id': 36, 'name': 'Yasin', 'juz': 22},
    {'id': 37, 'name': 'As-Saffat', 'juz': 23},
    {'id': 38, 'name': 'Sad', 'juz': 23},
    {'id': 39, 'name': 'Az-Zumar', 'juz': 23},
    {'id': 40, 'name': 'Ghafir', 'juz': 24},
    {'id': 41, 'name': 'Fussilat', 'juz': 24},
    {'id': 42, 'name': 'Asy-Syura', 'juz': 25},
    {'id': 43, 'name': 'Az-Zukhruf', 'juz': 25},
    {'id': 44, 'name': 'Ad-Dukhan', 'juz': 25},
    {'id': 45, 'name': 'Al-Jasiyah', 'juz': 25},
    {'id': 46, 'name': 'Al-Ahqaf', 'juz': 26},
    {'id': 47, 'name': 'Muhammad', 'juz': 26},
    {'id': 48, 'name': 'Al-Fath', 'juz': 26},
    {'id': 49, 'name': 'Al-Hujurat', 'juz': 26},
    {'id': 50, 'name': 'Qaf', 'juz': 26},
    {'id': 51, 'name': 'Az-Zariyat', 'juz': 26},
    {'id': 52, 'name': 'At-Tur', 'juz': 27},
    {'id': 53, 'name': 'An-Najm', 'juz': 27},
    {'id': 54, 'name': 'Al-Qamar', 'juz': 27},
    {'id': 55, 'name': 'Ar-Rahman', 'juz': 27},
    {'id': 56, 'name': 'Al-Waqi\'ah', 'juz': 27},
    {'id': 57, 'name': 'Al-Hadid', 'juz': 27},
    {'id': 58, 'name': 'Al-Mujadilah', 'juz': 28},
    {'id': 59, 'name': 'Al-Hasyr', 'juz': 28},
    {'id': 60, 'name': 'Al-Mumtahanah', 'juz': 28},
    {'id': 61, 'name': 'As-Saff', 'juz': 28},
    {'id': 62, 'name': 'Al-Jumu\'ah', 'juz': 28},
    {'id': 63, 'name': 'Al-Munafiqun', 'juz': 28},
    {'id': 64, 'name': 'At-Tagabun', 'juz': 28},
    {'id': 65, 'name': 'At-Talaq', 'juz': 28},
    {'id': 66, 'name': 'At-Tahrim', 'juz': 28},
    {'id': 67, 'name': 'Al-Mulk', 'juz': 29},
    {'id': 68, 'name': 'Al-Qalam', 'juz': 29},
    {'id': 69, 'name': 'Al-Haqqah', 'juz': 29},
    {'id': 70, 'name': 'Al-Ma\'arij', 'juz': 29},
    {'id': 71, 'name': 'Nuh', 'juz': 29},
    {'id': 72, 'name': 'Al-Jinn', 'juz': 29},
    {'id': 73, 'name': 'Al-Muzzammil', 'juz': 29},
    {'id': 74, 'name': 'Al-Muddassir', 'juz': 29},
    {'id': 75, 'name': 'Al-Qiyamah', 'juz': 29},
    {'id': 76, 'name': 'Al-Insan', 'juz': 29},
    {'id': 77, 'name': 'Al-Mursalat', 'juz': 29},
    {'id': 78, 'name': 'An-Naba\'', 'juz': 30},
    {'id': 79, 'name': 'An-Nazi\'at', 'juz': 30},
    {'id': 80, 'name': '\'Abasa', 'juz': 30},
    {'id': 81, 'name': 'At-Takwir', 'juz': 30},
    {'id': 82, 'name': 'Al-Infitar', 'juz': 30},
    {'id': 83, 'name': 'Al-Mutaffifin', 'juz': 30},
    {'id': 84, 'name': 'Al-Insyiqaq', 'juz': 30},
    {'id': 85, 'name': 'Al-Buruj', 'juz': 30},
    {'id': 86, 'name': 'At-Tariq', 'juz': 30},
    {'id': 87, 'name': 'Al-A\'la', 'juz': 30},
    {'id': 88, 'name': 'Al-Gasyiyah', 'juz': 30},
    {'id': 89, 'name': 'Al-Fajr', 'juz': 30},
    {'id': 90, 'name': 'Al-Balad', 'juz': 30},
    {'id': 91, 'name': 'Asy-Syams', 'juz': 30},
    {'id': 92, 'name': 'Al-Lail', 'juz': 30},
    {'id': 93, 'name': 'Ad-Duha', 'juz': 30},
    {'id': 94, 'name': 'Asy-Syarh', 'juz': 30},
    {'id': 95, 'name': 'At-Tin', 'juz': 30},
    {'id': 96, 'name': 'Al-\'Alaq', 'juz': 30},
    {'id': 97, 'name': 'Al-Qadr', 'juz': 30},
    {'id': 98, 'name': 'Al-Bayyinah', 'juz': 30},
    {'id': 99, 'name': 'Az-Zalzalah', 'juz': 30},
    {'id': 100, 'name': 'Al-\'Adiyat', 'juz': 30},
    {'id': 101, 'name': 'Al-Qari\'ah', 'juz': 30},
    {'id': 102, 'name': 'At-Takasur', 'juz': 30},
    {'id': 103, 'name': 'Al-\'Asr', 'juz': 30},
    {'id': 104, 'name': 'Al-Humazah', 'juz': 30},
    {'id': 105, 'name': 'Al-Fil', 'juz': 30},
    {'id': 106, 'name': 'Quraisy', 'juz': 30},
    {'id': 107, 'name': 'Al-Ma\'un', 'juz': 30},
    {'id': 108, 'name': 'Al-Kausar', 'juz': 30},
    {'id': 109, 'name': 'Al-Kafirun', 'juz': 30},
    {'id': 110, 'name': 'An-Nasr', 'juz': 30},
    {'id': 111, 'name': 'Al-Lahab', 'juz': 30},
    {'id': 112, 'name': 'Al-Ikhlas', 'juz': 30},
    {'id': 113, 'name': 'Al-Falaq', 'juz': 30},
    {'id': 114, 'name': 'An-Nas', 'juz': 30},
  ];

  static int getJuzForSurah(String surahName) {
    final surah = surahs.firstWhere(
      (s) => s['name'] == surahName,
      orElse: () => {'juz': 30},
    );
    return surah['juz'] as int;
  }
}
